background {
    path = ~/Pictures/Wallpaper/wp14806918.webp
    blur_passes = 4
    blur_size = 10
    brightness = 0.7
    contrast = 1.1
}

input-field {
    size = 320, 55
    position = 0, -80

    dots_center = true
    fade_on_empty = false

    font_family = Fira Code
    font_color = rgb(e6f1ff)

    inner_color = rgba(10, 18, 28, 0.65)
    outer_color = rgba(43, 127, 255, 0.8)

    outline_thickness = 2
    outline_color = rgba(74, 168, 255, 0.6)

    placeholder_text = "Enter password"
    placeholder_color = rgba(168, 191, 216, 0.6)

    shadow_passes = 2
    shadow_size = 10
    shadow_color = rgba(43, 127, 255, 0.3)
}

label {
    text = $TIME
    font_size = 64
    font_family = Fira Code

    color = rgb(e6f1ff)

    position = 0, 180
    halign = center
    valign = center
}
