# Tokyo Night

foreground            #c0caf5
background            #1a1b26

selection_foreground  #c0caf5
selection_background  #33467c

cursor                #c0caf5
cursor_text_color     #1a1b26

url_color             #73daca

active_border_color   #7aa2f7
inactive_border_color #292e42

# Black
color0  #15161e
color8  #414868

# Red
color1  #f7768e
color9  #ff899d

# Green
color2  #9ece6a
color10 #b9f27c

# Yellow
color3  #e0af68
color11 #ffcb6b

# Blue
color4  #7aa2f7
color12 #82aaff

# Magenta
color5  #bb9af7
color13 #caa6fe

# Cyan
color6  #7dcfff
color14 #86e1fc

# White
color7  #a9b1d6
color15 #c0caf5